services:
  - type: web
    name: flower-boda-api-dev
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EVENTS_SOURCE
        value: tour-api
      - key: TOUR_API_KEY
        sync: false
      - key: PLANTNET_API_KEY
        sync: false
      - key: PLANTNET_PROJECT
        value: all
